package main

func main() {

	/*
	   TODO:
	   1. CREATE A POSTGRES DATABASE CONTAINER COMPLETE WITH DB INITIALIZATION (STILL WANT TO HAVE A META-TABLE POINTING TO A DIRECTORY FOR MIGRATIONS, WHICH WILL BE NEXT)
	   2. CONNECT TO SAID CONTAINER WITH ENVIRONMENT VARIABLES
	   3. RUN A SELECT * QUERY ON A TABLE TO CONFIRM THE CONNECTION WORKS
	*/

}
