/*
TODO: THIS WILL NEED TO BE UPDATED WHEN I FIGURE OUT REGISTRY LAYOUT AND PROFILE PAGES. I KNOW I'LL NEED SOME FORM OF NAME INFO
*/
CREATE TABLE IF NOT EXISTS person (person_id SERIAL PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE);
