name: gift-registry

services:
  app:
    container_name: gift-registry-app
    image: golang
    command: go run ./cmd/api/main.go
    working_dir: /app
    volumes:
      - ..:/app
    ports:
      - "8080:8080"
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_PORT: ${EMAIL_PORT}
      MIGRATIONS_DIR: "internal/database/migrations"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_METRIC_EXPORT_INTERVAL: "5000" # so we don't have to wait 60s for metrics
      STATIC_FILES_DIR: cmd/web
      PORT: ${GR_PORT}
      TEMPLATES_DIR: "cmd/web/templates"
    networks:
      - gift-registry-network

networks:
  gift-registry-network:
