name: gift-registry

services:
  
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.14.2
    pull_policy: missing
    volumes:
      - type: bind
        source: ./open_observe_data
        target: /data
    ports: 
      - 5880:5080 # TODO: REMOVE THIS WHEN I INTEGRATE TRAEFICK
    # You'll need to include the following environment variables to pre-populate OpenObserve with an initial user the first time the container is run: ZO_ROOT_USER_EMAIL and ZO_ROOT_USER_PASSWORD. 
    # Once you start OpenObserve for the first time, create your own account and remove the environment variables
    environment:
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL} 
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD}

  postgres: 
    image: postgres:17.2
    pull_policy: missing
    volumes:
      - ./postgres_data:/var/lib/postgres/data
      - ./postgres_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Set up your DB credentials in environment variables
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
  app: 
    image: gift-registry
    pull_policy: missing
    depends_on: 
      - postgres
      - openobserve
    ports: 
      - "8080:8080" # TODO: REMOVE THIS WHEN I INTEGRATE TRAEFICK
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      TEMPLATES_DIR: "templates"
