name: gift-registry

services: 
  jaeger:
    image: gift-registry-jaeger
    build: jaeger
    pull_policy: missing
    container_name: jaeger
    expose: 
      - "4317"
      - "4318"
      - "8888"
      - "8889"
    ports: 
      - "18868:16686"
    networks:
      gift-registry:
        aliases: [spm_metrics_store]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m # TODO: EXPERIMENT WITH MAKING THIS SHORTER
      start_interval: 5s
    restart: unless-stopped
    command: ["--config", "/etc/jaeger/config.yml"]

  prometheus: 
    image: gift-registry-prometheus
    build: prometheus
    pull_policy: missing
    container_name: prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - "./data/jaeger:/tmp/jaeger"
      - "./data/jaeger_archive:/tmp/jaeger_archive"
    networks: 
      - gift-registry

  hotrod:
    image: jaegertracing/example-hotrod:latest
    container_name: hotrod
    ports:
      - "8080:8080"
      - "8083:8083"
    command: ["all"]
    environment: 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    networks:
      - gift-registry
    depends_on:
      - jaeger

networks: 
  gift-registry:
