name: gift-registry

services: 
  jaeger:
    image: jaegertracing/jaeger:2.1.0
    container_name: jaeger
    expose: 
      - "4317"
      - "4318"
      - "8888"
      - "8889"
    ports: 
      - "18868:16686"
    networks:
      gift-registry:
        aliases: [spm_metrics_store]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m # TODO: EXPERIMENT WITH MAKING THIS SHORTER
      start_interval: 5s
    restart: unless-stopped
    volumes: 
      - "../config/jaeger/jaeger-config.yml:/etc/jaeger/config.yml" 
    command: ["--config", "/etc/jaeger/config.yml"]

  prometheus: 
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - "../config/jaeger/prometheus-config.yml:/etc/prometheus/prometheus.yml" # TODO: GET CONFIGS FROM DEMO
    networks: 
      - gift-registry

  hotrod:
    image: jaegertracing/example-hotrod:latest
    container_name: hotrod
    ports:
      - "8080:8080"
      - "8083:8083"
    command: ["all"]
    environment: 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    networks:
      - gift-registry
    depends_on:
      - jaeger

networks: 
  gift-registry:
