name: gift-registry

services:
  app:
    container_name: gift-registry
    image: gift-registry
    pull_policy: if_not_present
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ${DB_PATH}:/app/database
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_PORT: ${EMAIL_PORT}
      MIGRATIONS_DIR: "migrations"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTLP_EXPORTER_ENDPOINT}
      OTEL_METRIC_EXPORT_INTERVAL: "5000" # so we don't have to wait 60s for metrics
      STATIC_FILES_DIR: "."
      PORT: ${GR_PORT}
      TEMPLATES_DIR: "templates"
    networks:
      - telemetry

networks:
  telemetry:
    name: local-bridge-network
    external: true
